web:
  image: dimaip/docker-neos-alpine:latest
  ports:
    - '80:80'
    #- '22:22'
  links:
    - db:db
  volumes:
    - /data
  environment:
    REPOSITORY_URL: 'https://github.com/patriceckhart/NeosCMS-Boilerplate'
    SITE_PACKAGE: 'Raw.Site'
    ADMIN_PASSWORD: 'yourpassphrase'
    IMPORT_GITHUB_PUB_KEYS: 'YOUR_GITHUB_USERNAME'

db:
  image: mariadb:latest
  expose:
    - 3306
  volumes:
    - /data
  environment:
    MYSQL_DATABASE: 'db'
    MYSQL_USER: 'admin'
    MYSQL_PASSWORD: 'pass'
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  ports:
    - '3306:3306'