Neos:
  Flow:
    i18n:
      defaultLocale: de
  Neos:
    eventLog:
      enabled: TRUE
    userInterface:
      defaultLanguage: de
    nodeTypes:
      groups:
        additional:
          position: 'end'
          label: 'Spezielle Inhaltselemente'