NeosRulez:
  DynamicResources:
    site:
      resources:
        head:
          styles:
            animateCss: 'resource://NeosRulez.Bootstrap/Private/Styles/animate.css'
            appCss: 'resource://Raw.Site/Private/Styles/app.scss'
        footer:
          scripts:
            fsLightboxJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/fslightbox.js'
            neosrulezBootstrapJs: '../Packages/Libraries/twbs/bootstrap/dist/js/bootstrap.bundle.js'
            jQuery: 'resource://NeosRulez.Bootstrap/Private/JavaScript/jquery-3.6.0.js'
            waypointsJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/waypoints.js'
            parallaxJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/parallax.js'
            neosrulezBootstrapAdditionalJs: 'resource://NeosRulez.Bootstrap/Private/JavaScript/scripts.js'
            appJs: 'resource://Raw.Site/Private/JavaScript/app.js'
