Neos:
  Neos:
    eventLog:
      enabled: TRUE
    userInterface:
      translation:
        autoInclude:
          Raw.Site:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        special:
          position: 'end'
          label: Raw.Site:Main:nodeTypes.groups.special
Raw:
  Site:
    pageTitle: 'Default'
NeosRulez:
  Bootstrap:
    headerLogoPath: 'Images/Logo.png'
    headerLogoPackage: 'Raw.Site'
    headerLogoAltText: 'RawSite'