Neos:
  Neos:
    userInterface:
      editPreviewModes:
        tablet:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Tablet'
          width: 768px
          height: 1024px
        mobile:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Mobile'
          width: 360px
          height: 640px